name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Install dtc
      run: sudo apt-get install device-tree-compiler
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-features
    - name: Unit test
      run: cargo test -- --nocapture
